apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  containers:
  - image: mongo
    name: mongo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
