apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  
spec:
  containers:
  - image: nginx
    name: nginx 
    volumeMounts:
    - name: nginx-volume
      mountPath: /etc/cfg
  volumes:
  - name: nginx-volume
    configMap:
      name: cfgvolume