apiVersion: v1
kind: Pod
metadata: 
  name: redis-pod
spec:
  containers:
  - name: redis-cont
    image: redis
    volumeMounts:
    - name: redis-vol-storage
      mountPath: /data/redis
  volumes:
  - name: redis-vol-storage
    emptyDir: {}